A = set('hola')
B = set('manola')

print('Los elementos únicos de A y B')
print(A)
print(B)
print('Elementos que están en A y no en B')
print(A-B)
print('Elementos que están en A o en B o en ambos')
print(A | B)
print('Elementos que están en A y B')
print(A & B)
print('Elementos que están en A o B pero no en ambos')
print(A^B)